### ISSUE TITLE
write/read tf broken by "comments"

### ISSUE THREAD

**Issue by kkappler** [kujaku11/mt_metadata#145]
Ran locally aurora/tests/io/test_issue_139.py and it passed.
Pulled mt_metadata on `fcs` branch and it now fails.
The error is when it read back in the tf that it just wrote:

```
 def test_tf_write_and_read(self):
        tf_obj = self.tf_obj
        tf_obj.write(fn=self.xml_file_base, file_type="emtfxml")

        tf_obj2 = TF()
        tf_obj2.read(fn=self.xml_file_base)
```

I will comment out this test for now in aurora, since aurora issue 139 is still open.

The error is:

> Traceback (most recent call last):
  File "test_issue_139.py", line 81, in test_tf_write_and_read
    tf_obj2.read(fn=self.xml_file_base)
  File "/home/kkappler/software/irismt/mt_metadata/mt_metadata/transfer_functions/core.py", line 1392, in read
    self._read_write_dict[file_type]["read"](self.fn, **kwargs)
  File "/home/kkappler/software/irismt/mt_metadata/mt_metadata/transfer_functions/core.py", line 1585, in from_emtfxml
    emtfxml_obj.read(self._fn)
  File "/home/kkappler/software/irismt/mt_metadata/mt_metadata/transfer_functions/io/emtfxml/emtfxml.py", line 309, in read
    attr.read_dict(root_dict)
  File "/home/kkappler/software/irismt/mt_metadata/mt_metadata/transfer_functions/io/emtfxml/metadata/site.py", line 107, in read_dict
    attr.read_dict(input_dict["site"])
  File "/home/kkappler/software/irismt/mt_metadata/mt_metadata/transfer_functions/io/emtfxml/metadata/data_quality_notes.py", line 49, in read_dict
    self.comments.read_dict(comments_dict)
  File "/home/kkappler/software/irismt/mt_metadata/mt_metadata/transfer_functions/io/emtfxml/metadata/comment.py", line 55, in read_dict
    self.value = key["value"]
KeyError: 'value'

**Comment by kujaku11** [comment]
@kkappler Issue fixed in mt_metadata fcs branch.  Closing for now.
