### ISSUE TITLE
python 3.7 install failing on fcs branch

### ISSUE THREAD

**Issue by kkappler** [kujaku11/mt_metadata#152]
Testing `fourier_coefficients` branch of aurora, passing on python 3.8, 3.9, 3.10, but not on 3.7
![image](https://github.com/kujaku11/mt_metadata/assets/1154939/0297fd24-e296-4c0a-8a6f-70832732638a)

@kujaku11 
Considering that obspy has moved to minimum supported branch of 3.8, I wonder if we should just drop 3.7 and move on?
![image](https://github.com/kujaku11/mt_metadata/assets/1154939/f41727c1-e38d-4189-aff4-595c4beb8113)

FWIW here is the traceback:

> Running command git checkout -b fcs --track origin/fcs
  Switched to a new branch 'fcs'
  branch 'fcs' set up to track 'origin/fcs'.
  Resolved https://github.com/kujaku11/mt_metadata.git to commit b266c11f75d9f5dff8a0732012387d1b7a8d3a86
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "/usr/share/miniconda/envs/aurora-test/lib/python3.7/site-packages/setuptools/__init__.py", line 18, in <module>
          from setuptools.dist import Distribution
        File "/usr/share/miniconda/envs/aurora-test/lib/python3.7/site-packages/setuptools/dist.py", line 33, in <module>
          from ._importlib import metadata
        File "/usr/share/miniconda/envs/aurora-test/lib/python3.7/site-packages/setuptools/_importlib.py", line 39, in <module>
          disable_importlib_metadata_finder(metadata)
        File "/usr/share/miniconda/envs/aurora-test/lib/python3.7/site-packages/setuptools/_importlib.py", line 12, in disable_importlib_metadata_finder
          import importlib_metadata
        File "/usr/share/miniconda/envs/aurora-test/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 6, in <module>
          import zipp
        File "/usr/share/miniconda/envs/aurora-test/lib/python3.7/site-packages/zipp/__init__.py", line 10, in <module>
          from .py310compat import text_encoding
        File "/usr/share/miniconda/envs/aurora-test/lib/python3.7/site-packages/zipp/py310compat.py", line 5
          def _text_encoding(encoding, stacklevel=2, /):
                                                     ^
      SyntaxError: invalid syntax
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Error: Process completed with exit code 1.

**Comment by kujaku11** [comment]
Remove dependency on 3.7, so we'll call this fixed.
